#!/usr/bin/env python3
"""Import supplied GaultonLab GMTs unchanged through DIG's external-import contract."""
from __future__ import annotations

import argparse
import csv
import os
import subprocess
import sys
from pathlib import Path


MODEL_LABELS = {
    "HZ1": "combined incoming and outgoing signaling genes",
    "HZ2": "incoming receptor genes",
    "HZ3": "outgoing ligand genes",
}


def read_tasks(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        return [row for row in csv.DictReader(handle, delimiter="\t") if row["enabled"] == "true"]


def read_input_map(path: Path) -> dict[tuple[str, str], Path]:
    with path.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        required = {"partition_id", "model_id", "input_gmt"}
        if not required <= set(reader.fieldnames or []):
            raise SystemExit(f"{path} must contain columns: partition_id, model_id, input_gmt")
        mapping: dict[tuple[str, str], Path] = {}
        for row in reader:
            key = (row["partition_id"].strip(), row["model_id"].strip())
            raw_path = row["input_gmt"].strip()
            if not key[0] or not key[1] or not raw_path:
                raise SystemExit(f"{path} has a blank partition_id, model_id, or input_gmt")
            candidate = Path(raw_path).expanduser()
            mapping[key] = (path.parent / candidate).resolve() if not candidate.is_absolute() else candidate.resolve()
    return mapping


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--smoke", action="store_true")
    mode.add_argument("--full", action="store_true")
    parser.add_argument("--out-root", required=True)
    parser.add_argument("--models", default="all")
    parser.add_argument("--partitions", default="all")
    parser.add_argument("--input-gmt-map", help="TSV with partition_id, model_id, and input_gmt columns; overrides directory/filename resolution.")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    workspace = root.parents[1]
    dig = Path(os.environ.get("DIG_REPO", workspace / "dig-gene-set-extractors")).resolve()
    if not (dig / "src/geneset_extractors").is_dir():
        raise SystemExit("DIG_REPO must identify a dig-gene-set-extractors checkout")
    source_dir = Path(os.environ.get("GAULTONLAB_GMT_DIR", workspace / "submissions/cfde_legacy/GaultonLab")).expanduser().resolve()
    map_value = args.input_gmt_map or os.environ.get("GAULTONLAB_GMT_MAP_TSV", "")
    input_map = read_input_map(Path(map_value).expanduser().resolve()) if map_value else {}
    if not input_map and not source_dir.is_dir():
        raise SystemExit("GAULTONLAB_GMT_DIR must identify the directory containing the supplied GMTs")
    models = None if args.models == "all" else {value.strip() for value in args.models.split(",") if value.strip()}
    partitions = None if args.partitions == "all" else {value.strip() for value in args.partitions.split(",") if value.strip()}

    env = {**os.environ, "PYTHONPATH": str(dig / "src") + (os.pathsep + os.environ["PYTHONPATH"] if os.environ.get("PYTHONPATH") else "")}
    for row in read_tasks(root / "config/task_manifest.tsv"):
        model_id, partition_id = row["model_id"], row["partition_id"]
        if (models is not None and model_id not in models) or (partitions is not None and partition_id not in partitions):
            continue
        gmt = input_map.get((partition_id, model_id), source_dir / row["gmt_filename"])
        if not gmt.is_file():
            raise SystemExit(f"missing supplied GMT: {gmt}")
        out_dir = Path(args.out_root).resolve() / f"genesets/{partition_id}/models/{model_id}/extractor"
        if out_dir.exists() and not args.overwrite:
            raise SystemExit(f"output already exists: {out_dir}; pass --overwrite to replace sidecars")
        display_name = f"GaultonLab {partition_id} {MODEL_LABELS[model_id]}"
        command = [
            sys.executable, "-m", "geneset_extractors.cli", "external-import",
            "--gmt", str(gmt), "--out-dir", str(out_dir),
            "--source-record", str(root / "config/source_record.json"),
            "--library-id", "GaultonLab", "--model-id", model_id,
            "--display-name", display_name,
            "--description", f"{display_name}, generated by the GaultonLab LIANA cell-cell communication pipeline and imported unchanged.",
            "--expected-sha256", row["sha256"],
        ]
        print("$ " + " ".join(command), flush=True)
        subprocess.run(command, check=True, env=env)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
