import csv
import json
import shutil
import sys
from pathlib import Path

import pytest

SRC = Path(__file__).resolve().parents[1] / "src"
sys.path.insert(0, str(SRC))
import run_cptac_ptm_model as runner  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[3]
DIG_DIR = REPO_ROOT / "dig-gene-set-extractors"
FIX = Path(__file__).resolve().parent / "fixtures"
CONFIG = Path(__file__).resolve().parents[1] / "config"


def _api_cache(tmp_path):
    import hashlib

    def md5(p):
        return hashlib.md5(Path(p).read_bytes()).hexdigest()

    phospho = json.loads((FIX / "files_per_study.ccrcc_phospho.json").read_text())
    phospho["data"]["filesPerStudy"][0]["md5sum"] = md5(FIX / "reports" / "CCRCC_Phosphoproteome.phosphosite.tmt10.tsv")
    proteome = json.loads((FIX / "files_per_study.ccrcc_proteome.json").read_text())
    proteome["data"]["filesPerStudy"][0]["md5sum"] = md5(FIX / "reports" / "CCRCC_Proteome.tmt10.tsv")
    biospec = json.loads((FIX / "biospecimen_per_study.ccrcc.json").read_text())
    out = tmp_path / "api_cache.json"
    out.write_text(json.dumps({"phospho_files": phospho, "proteome_files": proteome, "biospecimen": biospec}))
    return out


@pytest.mark.skipif(not DIG_DIR.exists(), reason="dig-gene-set-extractors checkout not found")
def test_run_model_offline_end_to_end(tmp_path):
    out_root = tmp_path / "cptac_outputs"
    model_dir = runner.run_model(
        dig_dir=DIG_DIR,
        cohort_id="ccrcc",
        model_id="PT1",
        out_root=out_root,
        config_dir=CONFIG,
        offline=True,
        source_dir=FIX / "reports",
        api_cache_json=_api_cache(tmp_path),
        python_bin=sys.executable,
    )
    # Model output standardizes on a workflow/ dir (formerly "prepared").
    assert (Path(model_dir) / "workflow").exists()
    assert (Path(model_dir) / "workflow" / "ptm_matrix.tsv").exists()
    assert not (Path(model_dir) / "prepared").exists()

    # Provenance overlay is now generated by the DIG `provenance overlay` subcommand
    # directly into model_out (no local wrapper module involved).
    assert (Path(model_dir) / "provenance_overlay.json").exists()
    source_map_path = Path(model_dir) / "local_input_source_map.tsv"
    assert source_map_path.exists()

    # Regression (C1): sample_annotations.tsv must be mapped in the source map to the
    # phospho study's PDC page, so refresh rewrites its local path instead of leaking it
    # into the published prepare-provenance `command`.
    with source_map_path.open(encoding="utf-8", newline="") as fh:
        source_map_rows = list(csv.DictReader(fh, delimiter="\t"))
    sample_annotations_rows = [
        row for row in source_map_rows if row["local_path"].endswith("sample_annotations.tsv")
    ]
    assert sample_annotations_rows, f"no sample_annotations.tsv row in {source_map_rows}"
    assert all(
        row["source_uri"] == "https://pdc.cancer.gov/pdc/study/PDC000128"
        for row in sample_annotations_rows
    )

    # At least one variant dir with the 3-file contract.
    provs = list(Path(model_dir).rglob("geneset.provenance.json"))
    assert provs, "no geneset.provenance.json produced"
    for prov in provs:
        assert (prov.parent / "geneset.tsv").exists()
        assert (prov.parent / "geneset.meta.json").exists()

    # Full-schema geneset.model.json sidecar alongside each variant.
    model_jsons = list(Path(model_dir).rglob("geneset.model.json"))
    assert model_jsons, "no geneset.model.json produced"
    variant_labels = set()
    for path in model_jsons:
        payload = json.loads(path.read_text())
        assert payload["library"] == "CPTAC"
        assert payload["model_group"] == "PT"
        assert payload["workflow_name"] == "ptm_prepare_public"
        assert payload["extractor_name"] == "ptm_site_matrix"
        assert isinstance(payload["parameters"], dict)
        assert isinstance(payload["inputs"], dict)
        assert isinstance(payload["naming"], dict)
        assert payload["inputs"]["cohort_id"] == "ccrcc"
        assert payload["naming"]["variant_label"] in {"ProteinAdjusted", "Unadjusted"}
        variant_labels.add(payload["naming"]["variant_label"])
    # compare_if_protein + a matched protein matrix should emit both variants.
    assert variant_labels == {"ProteinAdjusted", "Unadjusted"}
    # Workflow provenance graph is emitted by the DIG prepare step.
    assert (Path(model_dir) / "workflow" / "ptm_matrix.provenance_graph.json").exists()

    # Every emitted per-gene-set provenance records BOTH analysis steps, connected
    # through a single coalesced ptm_matrix.tsv bridge node.
    sample_annotations_node_seen = False
    for prov in provs:
        graph = json.loads(prov.read_text())
        graph = list(graph.values())[0] if "nodes" not in graph else graph
        methods = sorted(n["id"].split(":")[1] for n in graph["nodes"] if n["type"] == "AnalysisType")
        assert methods == ["ptm_prepare_public", "ptm_site_matrix"], f"{prov}: {methods}"

        ptm_nodes = [n for n in graph["nodes"] if n["type"] == "File" and n["name"] == "ptm_matrix.tsv"]
        assert len(ptm_nodes) == 1, f"{prov}: ptm_matrix.tsv should be one coalesced node"
        bridge_id = ptm_nodes[0]["id"]
        prepare_op = next(n for n in graph["nodes"] if n["id"].split(":")[1] == "ptm_prepare_public")
        convert_op = next(n for n in graph["nodes"] if n["id"].split(":")[1] == "ptm_site_matrix")
        edge_pairs = {(e["source"], e["target"]) for e in graph["edges"]}
        assert (prepare_op["id"], bridge_id) in edge_pairs
        assert (bridge_id, convert_op["id"]) in edge_pairs

        # A raw PDC report is present as an input to the prepare step.
        raw_names = {n["name"] for n in graph["nodes"] if n["type"] == "File"}
        assert any(name.endswith(".tsv") and "Phospho" in name for name in raw_names), raw_names

        # Regression (C1): sample_annotations.tsv is now a recorded provenance input node
        # (not just a bare local path embedded in the prepare-step command).
        if "sample_annotations.tsv" in raw_names:
            sample_annotations_node_seen = True
    assert sample_annotations_node_seen, "no geneset.provenance.json recorded a sample_annotations.tsv input node"

    # Publish-facing GMT set names: cohort-level signature + DIG-appended variant label,
    # no legacy '__signature=' scaffold.
    gmt_paths = list(Path(model_dir).rglob("genesets.gmt"))
    assert gmt_paths, "no genesets.gmt produced"
    set_names: set[str] = set()
    for gmt_path in gmt_paths:
        for line in gmt_path.read_text().splitlines():
            if not line.strip():
                continue
            set_names.add(line.split("\t", 1)[0])
    assert "CPTAC_ClearCellRCC_ProteinAdjusted_up" in set_names
    assert "CPTAC_ClearCellRCC_Unadjusted_up" in set_names
    assert not any("__signature=" in name for name in set_names)

    # genome_build must record the assembly ("hg38"), not the organism ("human").
    for path in model_jsons:
        meta_path = path.parent / "geneset.meta.json"
        meta_payload = json.loads(meta_path.read_text())
        assert meta_payload["gene_set"]["genome_build"] == "hg38"
        assert meta_payload["input"]["genome_build"] == "hg38"


def test_cohort_token():
    assert runner.cohort_token("Clear Cell RCC") == "ClearCellRCC"
    assert runner.cohort_token("Lung SCC") == "LungSCC"
    assert runner.cohort_token("Breast (Prospective)") == "Breast(Prospective)"


def _write_manifest(extractor_dir: Path, rows: list[dict[str, str]]) -> None:
    fieldnames = ["variant_id", "meta_path"]
    with (extractor_dir / "manifest.tsv").open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, delimiter="\t", fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def test_write_model_sidecars_full_schema(tmp_path):
    extractor_dir = tmp_path / "extractor"
    variant_dirs = {"none": extractor_dir / "none", "subtract": extractor_dir / "subtract"}
    for d in variant_dirs.values():
        d.mkdir(parents=True)
    _write_manifest(
        extractor_dir,
        [
            {
                "variant_id": f"protein_adjustment={adjustment}__gene_topk_sites=3",
                "meta_path": f"{d.name}/geneset.meta.json",
            }
            for adjustment, d in variant_dirs.items()
        ],
    )
    model = {
        "prepare_ptm_type": "phospho",
        "extractor_study_contrast": "condition_a_vs_b",
        "extractor_condition_a": "case",
        "extractor_condition_b": "control",
        "extractor_gene_aggregation": "signed_topk_mean",
        "extractor_select": "top_k",
        "extractor_top_k": "200",
    }

    runner.write_model_sidecars(
        extractor_dir=extractor_dir,
        model_id="PT1",
        cohort_id="ccrcc",
        cohort_label="Clear Cell RCC",
        phospho_pdc_study_id="PDC000128",
        proteome_pdc_study_id="PDC000127",
        model=model,
    )

    payloads = {}
    for adjustment, d in variant_dirs.items():
        sidecar = d / "geneset.model.json"
        assert sidecar.exists()
        payload = json.loads(sidecar.read_text())
        payloads[adjustment] = payload
        assert payload["schema_version"] == "1"
        assert payload["library"] == "CPTAC"
        assert payload["model_id"] == "PT1"
        assert payload["model_group"] == "PT"
        assert payload["workflow_name"] == "ptm_prepare_public"
        assert payload["extractor_name"] == "ptm_site_matrix"
        assert isinstance(payload["parameters"], dict)
        assert isinstance(payload["inputs"], dict)
        assert isinstance(payload["naming"], dict)
        assert payload["parameters"]["gene_topk_sites"] == 3
        assert payload["parameters"]["protein_adjustment"] == adjustment
        assert payload["inputs"]["cohort_id"] == "ccrcc"
        assert payload["inputs"]["phospho_pdc_study_id"] == "PDC000128"
        assert payload["inputs"]["proteome_pdc_study_id"] == "PDC000127"
        assert payload["naming"]["variant_label"] in {"ProteinAdjusted", "Unadjusted"}

    assert payloads["none"]["naming"]["variant_label"] == "Unadjusted"
    assert payloads["subtract"]["naming"]["variant_label"] == "ProteinAdjusted"
    assert payloads["none"]["naming"]["signature_name"] == "CPTAC_ClearCellRCC_Unadjusted"
    assert payloads["subtract"]["naming"]["signature_name"] == "CPTAC_ClearCellRCC_ProteinAdjusted"


def test_run_model_write_model_only_rewrites_existing_sidecars(tmp_path):
    out_root = tmp_path / "cptac_outputs"
    extractor_dir = out_root / "genesets" / "ccrcc" / "models" / "PT1" / "extractor"
    variant_dirs = {"none": extractor_dir / "none", "subtract": extractor_dir / "subtract"}
    for d in variant_dirs.values():
        d.mkdir(parents=True)
    _write_manifest(
        extractor_dir,
        [
            {
                "variant_id": f"protein_adjustment={adjustment}__gene_topk_sites=3",
                "meta_path": f"{d.name}/geneset.meta.json",
            }
            for adjustment, d in variant_dirs.items()
        ],
    )

    model_out = runner.run_model(
        dig_dir="/nonexistent/dig-dir-not-touched-in-write-model-only-mode",
        cohort_id="ccrcc",
        model_id="PT1",
        out_root=out_root,
        config_dir=CONFIG,
        write_model_only=True,
    )

    assert model_out == extractor_dir.parent
    # Skipped fetch/prepare/overlay/extract: no workflow dir, provenance overlay, or logs.
    assert not (model_out / "workflow").exists()
    assert not (model_out / "provenance_overlay.json").exists()
    assert not (model_out / "run.log").exists()

    for adjustment, d in variant_dirs.items():
        sidecar = d / "geneset.model.json"
        assert sidecar.exists()
        payload = json.loads(sidecar.read_text())
        assert payload["model_id"] == "PT1"
        assert payload["model_group"] == "PT"
        assert payload["inputs"]["cohort_id"] == "ccrcc"
        assert payload["parameters"]["protein_adjustment"] == adjustment


def test_run_model_write_model_only_noop_when_extractor_dir_absent(tmp_path):
    out_root = tmp_path / "cptac_outputs"

    model_out = runner.run_model(
        dig_dir="/nonexistent/dig-dir-not-touched-in-write-model-only-mode",
        cohort_id="ccrcc",
        model_id="PT1",
        out_root=out_root,
        config_dir=CONFIG,
        write_model_only=True,
    )

    # No extractor/ output ever existed for this model -> clean no-op, nothing created.
    assert not (model_out / "extractor").exists()
    assert not model_out.exists()
